--- #YAML:1.0
name:                Enbugger
version:             2.003
abstract:            Enables the debugger at runtime.
license:             perl
author:              
    - WhitePages.com, Inc <whitepage@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    B::Utils:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
