#!perl

# COPYRIGHT AND LICENCE
#
# Copyright (C) 2007,2008 WhitePages.com, Inc. with primary
# development by Joshua ben Jore.
#
# This program is distributed WITHOUT ANY WARRANTY, including but not
# limited to the implied warranties of merchantability or fitness for
# a particular purpose.
#
# The program is free software.  You may distribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation (either version 2 or any later version)
# and the Perl Artistic License as published by O’Reilly Media, Inc.
# Please open the files named gpl-2.0.txt and Artistic for a copy of
# these licenses.

use Enbugger;
use Enbugger::OnError;

eval {
    # Should not drop into the debugger. We're in an eval.
    die 'An exception';
};
print "Caught: $@\n";

# Should drop into the debugger. We're not in an eval anymore.
#Enbugger->load_debugger('perl5db');
Enbugger->stop


## Local Variables:
## mode: cperl
## mode: auto-fill
## cperl-indent-level: 4
## End:

